"""Export a small, stratified, keyword-diverse sample from the built databases
into docs/sample_data.js, so the GitHub Pages site can run a fully client-side
demo with no backend. Synthetic data only — no real PHI.

Usage:  python export_sample.py   (after etl.py has built the databases)
"""

import json
import sqlite3
from pathlib import Path

BASE = Path(__file__).parent
DOCS = BASE.parent / "docs"

# Terms to guarantee coverage of, so search/synonym demos are compelling.
SEED_TERMS = ["myocardial infarction", "hydrocephalus", "infarct", "hemorrhage",
              "aneurysm", "growth restriction", "mass", "seizure", "stenosis", "edema"]

clinical = sqlite3.connect(BASE / "clinical.db")
clinical.row_factory = sqlite3.Row
vault = sqlite3.connect(BASE / "vault.db")
vault.row_factory = sqlite3.Row

picked: dict[int, sqlite3.Row] = {}

# Seed on structured findings so the sample contains BOTH present and ruled-out
# examples of key findings — this is what makes the negation demo work client-side.
SEED_FINDINGS = ["Hydrocephalus", "Hemorrhage", "Infarct", "Stenosis", "Aneurysm",
                 "Mass Effect", "Cardiomegaly", "Growth Restriction", "Edema"]
for value in SEED_FINDINGS:
    for status, n in (("present", 3), ("absent", 2)):
        for r in clinical.execute(
            "SELECT s.* FROM studies s JOIN finding_tags t ON t.study_key=s.study_key "
            "WHERE t.value_lc LIKE ? AND t.status=? LIMIT ?", (f"%{value.lower()}%", status, n)):
            picked[r["study_key"]] = r

# A few records per free-text seed term too (keyword-search variety).
for term in SEED_TERMS:
    for r in clinical.execute(
        "SELECT s.* FROM studies_fts f JOIN studies s ON s.study_key=f.rowid "
        "WHERE studies_fts MATCH ? LIMIT 2", (f'"{term}"',)):
        picked[r["study_key"]] = r

# Fill to a balanced ~20 per hospital.
for hosp in ("BCH", "MGH", "BWH"):
    have = sum(1 for r in picked.values() if r["hospital"] == hosp)
    for r in clinical.execute(
        "SELECT * FROM studies WHERE hospital=? ORDER BY RANDOM() LIMIT ?", (hosp, max(0, 20 - have))):
        picked[r["study_key"]] = r

vkeys = {r["patient_key"]: r for r in vault.execute("SELECT * FROM patients")}

sample = []
for r in picked.values():
    p = vkeys[r["patient_key"]]
    findings = [{"dimension": t["dimension"], "value": t["value"], "status": t["status"]}
                for t in clinical.execute(
                    "SELECT dimension, value, status FROM finding_tags WHERE study_key=? ORDER BY dimension, value",
                    (r["study_key"],))]
    sample.append({
        "hospital": r["hospital"],
        "study_id": r["study_id"],
        "patient_key": r["patient_key"],
        "patient_name": p["patient_name"],
        "patient_id": p["patient_id"],
        "birth_date": p["birth_date"],
        "age_years": r["age_years"],
        "sex": r["sex"],
        "study_date": r["study_date"],
        "modality": r["modality"],
        "body_part": r["body_part"],
        "generic_category": r["generic_category"],
        "findings": findings,
        "diagnosis": r["diagnosis"],
    })

sample.sort(key=lambda x: (x["hospital"], x["study_id"]))
DOCS.mkdir(exist_ok=True)
out = DOCS / "sample_data.js"
out.write_text("// Auto-generated by solution/export_sample.py — synthetic sample for the client-side demo.\n"
               "window.DAB_SAMPLE = " + json.dumps(sample, indent=0) + ";\n", encoding="utf-8")
print(f"Wrote {len(sample)} records to {out}")
print("  by hospital:", {h: sum(1 for x in sample if x['hospital'] == h) for h in ('BCH', 'MGH', 'BWH')})
